[build]
buildCommand = "cd server && npm install"

[deploy]
startCommand = "cd server && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "3001"